if(typeof HGSave!=='undefined'){
 let record={bestStage:0,bestKills:0},wasPlaying=false;
 const int=(v,a,b)=>Number.isInteger(v)&&v>=a&&v<=b;
 function valid(d){if(!d||!d.record||!int(d.record.bestStage,0,6)||!int(d.record.bestKills,0,100000000))return false;if(!d.run)return true;const r=d.run,g=r.g;if(!g||!CHARS[g.char]||!DIFFS[r.diff]||!int(g.stage,1,6)||!Number.isFinite(g.hp)||g.hp<=0||!Number.isFinite(g.t)||g.t<0||!int(g.level,1,10000)||!int(r.eid,0,100000000)||!int(r.queue,0,1000)||!r.timers||!Number.isFinite(r.elapsed)||r.elapsed<0)return false;
  for(const [key,defs]of [['weapons',WDEF],['passives',PDEF],['rares',RDEF]])if(!g[key]||Object.keys(g[key]).some(k=>!defs[k]||!int(g[key][k],0,10000)))return false;
  for(const key of ['enemies','bullets','ebullets','gems','orbs','texts','fxs','drops'])if(!Array.isArray(g[key])||g[key].some(x=>!x||typeof x!=='object'||Array.isArray(x)))return false;
  for(const key of ['bullets','ebullets','gems','texts','fxs','drops'])if(g[key].some(x=>!Number.isFinite(x.x)||!Number.isFinite(x.y)))return false;
  for(const key of ['bullets','ebullets'])if(g[key].some(x=>!['vx','vy','life','r','dmg'].every(k=>Number.isFinite(x[k]))))return false;
  if(g.bullets.some(x=>!WDEF[x.k]||!x.hit)||g.orbs.some(x=>!Number.isFinite(x.a))||g.texts.some(x=>typeof x.str!=='string')||g.drops.some(x=>typeof x.type!=='string'))return false;
  if(g.bosses&&(!Array.isArray(g.bosses)||g.bosses.some(b=>!b||!g.enemies.some(e=>e.id===b.id))))return false;
  if(g.zones&&(!Array.isArray(g.zones)||g.zones.some(z=>!z||!['x','y','r','t','tt','dmg'].every(k=>Number.isFinite(z[k])))))return false;
  return g.enemies.every(e=>Number.isInteger(e.id)&&Number.isFinite(e.hp)&&e.hitCD&&Number.isFinite(e.x)&&Number.isFinite(e.y))&&['px','py','soul','xp','startReal','totalKills','spawnAcc','eliteT','waveT','camx','camy'].every(k=>Number.isFinite(g[k]));
 }
 const auto=HGSave.mount('survivors',{validate:valid,interval:5000,progress(d){record=d.record;},note:'プレイ中の じょうたいと さいこうきろくを ほぞん。さいかいは いちじていし がめんから。',pause(){wasPlaying=state==='play';if(wasPlaying)togglePause();},unpause(){wasPlaying=false;},capture(old){if(G&&!bossTest){record.bestStage=Math.max(record.bestStage,G.stage);record.bestKills=Math.max(record.bestKills,G.totalKills);if(['play','pause'].includes(state)&&G.hp>0)return {record,run:{g:HGSave.clone(G),diff:Object.keys(DIFFS).find(k=>DIFFS[k]===DIFF),eid,elapsed:Date.now()-G.startReal,queue:levelQueue,timers:{...wTimers}}};if(state==='over'||state==='clear'&&G.stage===6)return {record,run:null};}return {record,run:old?.run||null};},restore(d){record={bestStage:Math.max(record.bestStage,d.record.bestStage),bestKills:Math.max(record.bestKills,d.record.bestKills)};if(!d.run){show('menu');state='menu';return;}const r=d.run;G=HGSave.clone(r.g);G.startReal=Date.now()-(r.elapsed||0);DIFF=DIFFS[r.diff];eid=r.eid;levelQueue=r.queue;selChar=G.char;bossTest=false;for(const k in wTimers)delete wTimers[k];Object.assign(wTimers,r.timers);G.bosses=(G.bosses||[]).map(b=>G.enemies.find(e=>e.id===b.id)).filter(Boolean);G.boss=G.bosses[0]||null;recalcChar();EGRID.clear();BGRID.clear();ecoReset();audioInit();resumeAudio();state='play';togglePause();last=performance.now();}});
}
