'use strict';
const assert=require('assert/strict'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/index.html','utf8'),scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]);const mod={exports:{}};new Function('module',scripts[0])(mod);const {Engine,CARDS}=mod.exports;let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
test('60種類・各段階12種類・全60枚に異なるquest画像',()=>{assert.equal(CARDS.length,60);assert.equal(new Set(CARDS.map(c=>c.name)).size,60);for(let tier=1;tier<=5;tier++)assert.equal(CARDS.filter(c=>c.tier===tier).length,12);const art=JSON.parse(fs.readFileSync(__dirname+'/art.json'));assert.equal(Object.keys(art.cards).length,60);assert.equal(new Set(Object.values(art.cards).map(a=>a.source)).size,60);for(const c of CARDS){const a=art.cards[c.id];assert.equal(a.actor,['taichi','kento','nozomi','erika','yushi'][c.f]);assert(art.sheets[a.sheet].startsWith('data:image/webp;base64,'));for(const k of ['x','y','bx','by'])assert(Number.isFinite(a.crop[k]));}});
test('満員でも3枚目を購入・合成できる',()=>{const e=new Engine(1),p=e.players[0];[0,1,2,3,4,0,5,6].forEach(id=>e.add(p,e.unit(id)));p.gold=3;p.shop[0]=0;assert(e.buy(p,0));assert.equal(p.board.length+p.bench.length,7);assert.equal(p.board.filter(u=>u.id===0&&u.star).length,1);assert.equal(p.rewards.length,1);});
test('新能力のシールドと遠距離攻撃が実際のダメージに反映',()=>{let e=new Engine(8),a=e.players[0],b=e.players[1];a.leader=b.leader=0;a.board=[e.unit(24)];b.board=[e.unit(5)];let r=e.battle(a,b);assert(r.frames.some(f=>f.label==='シールド！'));assert(r.frames.some(f=>f.type==='damage'&&f.numbers.some(n=>n.side===0&&n.value===0)));e=new Engine(9);e.round=2;a=e.players[0];b=e.players[1];a.leader=b.leader=0;a.board=[e.unit(26)];b.board=[e.unit(5)];r=e.battle(a,b);const hit=r.frames.find(f=>f.type==='damage');assert.equal(hit.numbers.find(n=>n.side===0).value,0);});
test('新能力の回復・開始時支援・継続成長・退場バフ',()=>{let e=new Engine(3),a=e.players[0],b=e.players[1];a.leader=b.leader=0;a.board=[e.unit(25),e.unit(3)];b.board=[e.unit(9)];let r=e.battle(a,b);assert(r.frames.some(f=>f.text.includes('かいふく')));e=new Engine(3);a=e.players[0];b=e.players[1];a.leader=b.leader=0;a.board=[e.unit(27),e.unit(0)];b.board=[e.unit(5)];r=e.battle(a,b);assert(r.frames.some(f=>f.text.includes('はつめい おうえん')));a.board=[e.unit(28)];const attack=a.board[0].a;e.phase='result';e.next();assert.equal(a.board[0].a,attack+1);e=new Engine(2);a=e.players[0];b=e.players[1];a.leader=b.leader=0;a.board=[e.unit(29),e.unit(0)];b.board=[e.unit(9),e.unit(5)];r=e.battle(a,b);assert(r.frames.some(f=>f.text.includes('バトンが')));});
test('同点順位・順位の上下・脱落順位の表示用データ',()=>{const e=new Engine(1);assert(e.standings().every(p=>p.place===1));e.previousStandings=e.standings();e.players[0].hp=20;const current=e.standings();assert.equal(current.find(p=>p.id===0).place,8);assert.equal(current.find(p=>p.id===1).place,1);e.players[0].hp=0;e.players[0].rank=8;assert(e.standings().at(-1).out);});
test('40試合の各ラウンド保存復元は次の結果まで一致',()=>{for(let seed=1;seed<=40;seed++){const e=new Engine(seed,seed%5);for(let i=0;i<20&&e.players[0].hp>0&&e.phase!=='end';i++){if(e.phase==='result')e.next();e.ai(e.players[0]);const saved=e.checkpoint(),copy=Engine.restore(saved);e.fight();copy.fight();assert.deepEqual(copy.players,e.players);assert.equal(copy.seed,e.seed);assert.deepEqual(copy.dead,e.dead);}}});
test('不正な保存データ・二重UID・重複対戦を拒否',()=>{const e=new Engine(1);e.buy(e.players[0],0);const data=e.checkpoint();let bad=structuredClone(data);bad.players[0].gold=-1;assert.throws(()=>Engine.restore(bad));bad=structuredClone(data);bad.pairs[0]=[0,0];assert.throws(()=>Engine.restore(bad));bad=structuredClone(data);bad.players[0].bench=[structuredClone(bad.players[0].board[0])];assert.throws(()=>Engine.restore(bad));bad=structuredClone(data);bad.rng='broken';assert.equal(typeof Engine.restore(bad).rng,'function');});
function uiSandbox(){const noop=()=>{},ctx=new Proxy({createLinearGradient:()=>({addColorStop:noop})},{get:(o,k)=>o[k]||noop,set:(o,k,v)=>(o[k]=v,true)}),elements={};const doc={hidden:false,getElementById:id=>elements[id]||=id==='game'?{style:{},getContext:()=>ctx,addEventListener:noop,getBoundingClientRect:()=>({left:0,top:0,width:960,height:540})}:{replaceChildren:noop,showModal:noop,close:noop,focus:noop,select:noop,value:'',textContent:''},createElement:()=>({})};const s={assert,console,structuredClone,setTimeout:()=>1,clearTimeout:noop,innerWidth:960,innerHeight:540,addEventListener:noop,document:doc,TextEncoder,TextDecoder,CompressionStream,DecompressionStream,Response,Blob,btoa,atob};vm.createContext(s);scripts.forEach(code=>vm.runInContext(code,s));return s;}
test('上下配置・全カード詳細・図鑑・売却取り消し・長押しの分離',()=>{const s=uiSandbox();vm.runInContext(`start();const p=g.players[0];p.shop=[24,0,1,2];purchase(0);fxAge=1000;render();const ownButton=buttons.find(b=>b.label.includes('おまもり'));assert(ownButton.y>380);const shops=buttons.filter(b=>b.y===109);assert(shops.length>0);ownButton.fn();assert(modal.detail);assert(modal.origin.owned);buttons.find(b=>b.label==='ならべかえる').fn();assert(selected!==null);choose(null,'bench',0);assert.equal(p.bench.length,1);showDetail(p.bench[0],{owned:true});buttons.find(b=>b.label==='うる +1コイン').fn();buttons.find(b=>b.label==='うる').fn();assert.equal(p.bench.length,0);undo();assert.equal(g.players[0].bench.length,1);for(const d of CARDS){modal=null;showDetail({...d,star:false});render();closeModal();showDetail({...d,star:true});render();closeModal();}modal='catalog';for(catalogPage=0;catalogPage<8;catalogPage++)render();modal=null;screen='prep';render();const unitButton=buttons.find(b=>b.inspect&&b.y===266);releasePointerDown({button:0,clientX:unitButton.x+5,clientY:unitButton.y+5,pointerId:1});press.long=true;press.b.inspect();releasePointerUp({clientX:unitButton.x+5,clientY:unitButton.y+5,pointerId:1});assert(modal.detail);closeModal();showFight();screen='result';render();assert(buttons.some(b=>b.label==='つぎの おみせ →'||b.label==='さいごの けっか →'));`,s);});
(async()=>{const s=uiSandbox();await vm.runInContext(`(async()=>{start();g.buy(g.players[0],0);const code=await encodeSave(g);const restored=await decodeSave(code);assert.equal(JSON.stringify(restored.players),JSON.stringify(g.players));await assert.rejects(()=>decodeSave(code.slice(0,-2)+'zz'));assert(code.length<10000);})()`,s);console.log('PASS あいことば圧縮・チェックサム・復元');console.log('RELEASE GATE: ALL PASS ('+(count+1)+' groups)');})().catch(e=>{console.error(e);process.exitCode=1;});

test('チュートリアル全10段階を実ボタンで完走・通常試合を保護',()=>{const s=uiSandbox();vm.runInContext(`
start();const before=JSON.stringify(g.checkpoint());startTutorial();
const click=label=>{const b=buttons.find(b=>b.label===label);assert(b,label);b.fn();};
click('3コインで かう');assert.equal(tutorial.engine.players[0].gold,0);click('できた！ つぎへ →');
click('ロボづくり の せつめい');assert(modal.detail);closeModal();click('できた！ つぎへ →');
click('ロボづくり の せつめい');click('はやわざ の せつめい');assert.equal(tutorial.engine.players[0].board[0].id,1);click('できた！ つぎへ →');
const battle=()=>{click('バトルを はじめる');let guard=0;while(buttons.some(b=>b.label==='つぎの うごき →')){assert(++guard<200);click('つぎの うごき →');}click('できた！ つぎへ →');};
battle();assert.equal(tutorial.step,4);click('できた！ つぎへ →');click('9コインで ★4に そだてる');assert.equal(tutorial.engine.players[0].tier,4);click('できた！ つぎへ →');
click('3コインで かう');assert(tutorial.engine.players[0].board[0].star);click('できた！ つぎへ →');click('これにする');assert(tutorial.engine.players[0].board.some(u=>CARDS[u.id].tier===5));click('できた！ つぎへ →');battle();assert.equal(tutorial.step,9);assert.equal(tutorial.result.starDamage,3);assert.equal(tutorial.result.lateDamage,1);
assert.equal(JSON.stringify(g.checkpoint()),before);click('もういちど れんしゅう');assert.equal(tutorial.step,0);click('おわる');assert.equal(screen,'title');assert.equal(tutorial,null);assert.equal(JSON.stringify(g.checkpoint()),before);
startTutorial();tutorial.step=9;render();click('ほんばんで あそぶ →');assert.equal(screen,'prep');assert.equal(g.round,1);assert.equal(tutorial,null);
`,s);});
