// Release UI. Canvas stays 960×540; all interactions have a keyboard equivalent.
let difficulty=1,catalogPage=0,detailReturn=null,press=null,holdTimer=null,undoState=null,guideStep=-1;
const artwork={};
const SHORT={...SKILL_LABEL,shield:'シールド',heal:'かいふく',snipe:'はんげき なし',rally:'はつめい おうえん',train:'まいターン そだつ',legacy:'バトン'};
const MARK={summon:'⚙',double:'×2',cheer:'♫',guard:'盾',grow:'↑',buff:'＋',none:'◇',shield:'◈',heal:'♥',snipe:'➶',rally:'⚙',train:'↑',legacy:'★'};
function describe(u){const d=CARDS[u.id],n=u.star?2:1;if(!d)return ['なかまの わざで でてくる ロボだよ。','このバトルだけ おてつだいするよ。'];const effect={summon:[`おやすみすると ${(d.tier===5?14:d.tier)*n+1}/${(d.tier===5?14:d.tier)*n+1}の ロボを 1たい よぶ。`,'チームが5たいの ときは よべないよ。'],double:['じぶんの ばんに 2かい こうげきする。','1かいめで おやすみすると 2かいめは できないよ。'],cheer:[`となりが こうげきするたび そのこの こうげき +${(d.tier===5?4:1)*n}。`,'ひだり・みぎ、どちらの となりにも とどくよ。'],guard:['あいては このこを ゆうせんして ねらう。','まもるこが なんにんか いると ランダムだよ。'],grow:[`ロボが でるたび じぶんの こうげき・たいりょく +${(d.tier===5?4:1)*n}。`,'ロボを よぶ なかまと くむと つよいよ。'],buff:['おみせで かうと チームの ほかの なかま +1/+1。','ひかえには とどかない。ごほうびで もらうと はつどうしない。'],none:['とくべつな わざは ないけれど、','こうげきと たいりょくの バランスが よいよ。'],shield:['さいしょに うける ダメージを 1かい 0にする。','はんげきの ダメージも ふせげるよ。'],heal:[`こうげきの あと きずの おおきい なかまを ${ (d.tier+1)*n }かいふく。`,'じぶんが おやすみすると かいふくできないよ。'],snipe:['じぶんから こうげきした とき はんげきを うけない。','あいてから ねらわれると ダメージを うけるよ。'],rally:[`バトルの はじめ ほかの「はつめい」の こうげき +${d.tier*n}。`,'じぶんには とどかないよ。'],train:[`つぎの おみせが はじまるたび じぶん +${(d.tier===5?4:1)*n}/+${(d.tier===5?4:1)*n}。`,'チームに いるときだけ。ひかえでは そだたないよ。'],legacy:[`おやすみすると のこった なかま みんな +${d.tier*n}/+${d.tier*n}。`,'いっしょに おやすみした なかまには とどかないよ。']};return [...effect[d.skill],...(d.tier===5?['かって のこると あいてへの ダメージ +3！']:[]),['buff','train'].includes(d.skill)?'この つよさは つぎの バトルにも のこるよ。':'この わざの こうかは このバトルだけだよ。'];}
function loadArt(){if(typeof Image==='undefined')return;for(const [key,url] of Object.entries(ART.sheets)){const im=new Image();artwork[key]=im;im.onload=()=>render();im.onerror=()=>{artwork[key]=null;render();};im.src=url;}}
function art(u,x,y,w,h){const m=ART.cards[u.id],im=m&&artwork[m.sheet];if(im?.complete&&im.naturalWidth){const c=m.crop,sw=im.naturalWidth*100/c.bx,sh=im.naturalHeight*100/c.by,sx=(im.naturalWidth-sw)*c.x/100,sy=(im.naturalHeight-sh)*c.y/100;const scale=Math.min(w/sw,h/sh),dw=sw*scale,dh=sh*scale;ctx.save();ctx.beginPath();ctx.roundRect(x,y,w,h,5);ctx.clip();ctx.fillStyle="#eae7da";ctx.fillRect(x,y,w,h);ctx.imageSmoothingEnabled=true;ctx.drawImage(im,sx,sy,sw,sh,x+(w-dw)/2,y+(h-dh)/2,dw,dh);ctx.restore();return true;}return false;}
function wrap(t,x,y,max=560,size=18){let line='',row=0;for(const ch of t){if(line.length*size>max){text(line,x,y+row*27,size,'#dce9e6');row++;line='';}line+=ch;}text(line,x,y+row*27,size,'#dce9e6');return y+(row+1)*27;}
function showDetail(u,origin=null){detailReturn=modal;modal={detail:structuredClone(u),origin};render();}
function closeModal(){if(modal?.detail){modal=detailReturn;detailReturn=null;}else modal=null;render();}
function card(u,x,y,w=120,h=98,fn=null){
 if(fn&&fx?.type==='buy'&&u?.uid===fx.u.uid&&fxAge<950)u=null;
 if(!u){rect(x,y,w,h,'#172c39');text('＋',x+w/2,y+h/2+7,24,'#658798','center');if(fn)buttons.push({label:'あいている ばしょ',x,y,w,h,fn});return;}
 const d=CARDS[u.id]||{f:0,name:'ちびロボ',tier:0,skill:'none'};
 rect(x,y,w,h,selected===u.uid?'#ffe39c':u.star?'#cba561':'#527786');rect(x+2,y+2,w-4,h-4,'#17313e');
 if(!art(u,x+5,y+23,w-10,h-64)){
  if(u.id===-1){rect(x+w/2-17,y+26,34,26,'#97c5cd');rect(x+w/2-11,y+33,7,7,'#fff0a0');rect(x+w/2+5,y+33,7,7,'#fff0a0');}
  else portrait(d.f,x+w/2-14,y+24,2);
 }
 text((u.star?'★ ':'')+d.name,x+w/2,y+17,Math.min(16,(w-12)/(d.name.length+(u.star?2:0))),u.star?'#ffe29b':'#f4eee0','center');
 rect(x+5,y+h-39,w-10,17,'#234a59',3);text(SHORT[d.skill]||'おてつだい',x+w/2,y+h-26,Math.min(13,(w-12)/(SHORT[d.skill]||'おてつだい').length),'#e3e9dc','center');
 text('⚔ '+u.a,x+9,y+h-5,18,'#ffe19c');text('♥ '+Math.max(0,u.h),x+w-8,y+h-5,18,'#ffb6c1','right');
 if(d.tier){rect(x+6,y+25,30,17,'#1d3946d9',3);text('★'+d.tier,x+21,y+38,12,'#ffe09c','center');}
 if(u.shield){text('◈',x+w-12,y+40,23,'#a9eaff','right');}
 if(screen==='battle'){const max=Math.max(1,u.maxH||u.h);rect(x+3,y+h+1,w-6,4,'#463345',2);rect(x+3,y+h+1,(w-6)*Math.max(0,u.h)/max,4,'#87dcbb',2);}
 // Every visible card, including replay, opponents and rewards, can be inspected.
 if((fx&&screen==='prep')||modal?.detail||modal?.sell)return;
 const owned=screen==='prep'&&g&&[...g.players[0].board,...g.players[0].bench].some(v=>v.uid===u.uid);
 const inspect=()=>showDetail(u,owned?{owned:true}:null);buttons.push({label:d.name+' の せつめい',x,y,w,h,fn:fn||inspect,inspect});
}
function checkpointUndo(){undoState=JSON.stringify(g.checkpoint());}
function undo(){if(!undoState)return;try{g=Engine.restore(JSON.parse(undoState));undoState=null;selected=null;notice='うるまえに もどしたよ';render();}catch{undoState=null;}}
function doAction(fn){undoState=null;act(fn);}
function start(){fx=null;paused=false;elapsed=0;g=new Engine(Date.now(),leader);g.difficulty=difficulty;screen='prep';selected=null;modal=null;undoState=null;guideStep=-1;notice='おみせで なかまを かおう！';render();}
function choose(u,key,i){if(selected!==null&&selected!==u?.uid){doAction(()=>g.place(g.players[0],selected,key,i));selected=null;render();}else if(u)showDetail(u,{owned:true});}
function drawPrep(){const p=g.players[0],pair=g.pairs.find(a=>a.includes(0)),oid=pair.find(id=>id!==0),op=g.players[oid>=0?oid:-oid-2];
 text('おみせ '+ '★'.repeat(p.tier)+'　/　1まい 3コイン',24,99,17,'#f4d895');
 for(let i=0;i<4;i++){const id=p.shop[i],d=CARDS[id];card(id===null?null:{...d,id,star:false},24+i*164,109,153,122,id===null?null:()=>{modal={detail:{...d,id,star:false},origin:{shop:i}};detailReturn=null;render();});}
 rect(696,86,240,146,'#263e47');text('コイン '+p.gold,715,116,24,'#ffe09a');
 button(p.tier===5?'さいこうレベル':'そだてる '+g.cost(p)+'コイン',708,131,215,42,()=>{doAction(()=>g.upgrade(p));},p.tier<5&&p.gold>=g.cost(p));
 button('ひきなおす '+(p.free?'0':'1'),708,181,129,40,()=>doAction(()=>g.refresh(p)),p.gold>0||p.free>0);
 button(p.freeze?'❄ ON':'キープ',845,181,79,40,()=>{p.freeze=!p.freeze;undoState=null;render();},true,p.freeze?'#867445':'#285969');
 text('ひかえ（3わく）',24,255,15,'#b3c8d2');for(let i=0;i<3;i++)card(p.bench[i],24+i*117,266,108,88,()=>choose(p.bench[i],'bench',i));
 text('つぎ：'+op.name+(oid<0?'の おばけ':''),398,265,17,'#e5d9b9');
 button('あいてを みる',398,282,161,42,()=>{modal='opponent';render();});button('カードずかん',569,282,137,42,()=>{modal='catalog';render();});
 if(p.rewards.length)button('★ ごほうび '+p.rewards.length,716,282,208,42,()=>{modal='reward';render();},true,'#967036');else button('あいことば',716,282,208,42,openSave);
 text(selected?'いどうさきの カード・あきわくを タップ':(p.tier>=4?'3まいで ★5！ おみせ★5の 1わくは 1%で ★5。':'タップ / ながおしで カードの せつめい。'),398,348,14,selected?'#ffe2a0':'#aac8d1');
 text('あなたの チーム　← ひだりから こうげき',24,380,18,'#aee6e4');
 for(let i=0;i<5;i++)card(p.board[i],24+i*134,392,124,114,()=>choose(p.board[i],'board',i));
 button(selected?'いどうを やめる':'じゅんび OK →',708,392,216,60,()=>{if(selected){selected=null;render();return;}if(p.rewards.length){modal='reward';render();return;}if(!p.board.length){modal='empty';render();return;}showFight();},true,'#a77837');
 button(undoState?'うるまえに もどす':'みんなの じゅんい',708,466,216,40,()=>{if(undoState)undo();else {modal='ranks';render();}});
 text(notice||'コインは もちこせないよ。おなじ3まいで ★スター！',24,532,14,'#c9d8d8');
}
function drawStandings(){const rows=g.standings(),prev=g.previousStandings||[],r=g.results.find(r=>r.x===0||r.y===0),win=r?.winner===0,draw=r?.winner===-1;
 text(draw?'ひきわけ！':win?'かった！':'つぎは くふうしよう！',24,113,27,'#ffe3a6');text('ハート '+oldHearts+' → '+Math.max(0,g.players[0].hp),605,112,23,'#ffbdc4');
 text('ダメージ '+(r?.damage||0)+'（★5 +'+(r?.starDamage||0)+' / けっせん +'+(r?.lateDamage||0)+'）　おなじ ハートは おなじ じゅんい',24,144,15,'#adc7d0');
 text('じゅんい',43,171,14,'#86aebb');text('なまえ',168,171,14,'#86aebb');text('ハート',470,171,14,'#86aebb');text('へんどう',616,171,14,'#86aebb');text('けっか',802,171,14,'#86aebb');
 rows.forEach((p,i)=>{const y=183+i*33,old=prev.find(a=>a.id===p.id),delta=old?old.place-p.place:0,change=delta>0?'↑ '+delta:delta<0?'↓ '+(-delta):'→ そのまま';rect(24,y,912,30,p.id===0?'#4d5846':i%2?'#193440':'#223e48',5);text(p.place+'い',45,y+21,18,'#ffe2a1');text(p.name,168,y+21,17,p.id===0?'#ffe3a3':'#d9e8e8');text('♥ '+p.hp+(old&&old.hp!==p.hp?'  (−'+(old.hp-p.hp)+')':''),470,y+21,16,'#ffc0c4');text(change,616,y+21,16,delta>0?'#a1e7b8':delta<0?'#f5b6b3':'#b9cbd0');text(p.out?'だつらく':p.place===1&&g.phase==='end'?'ゆうしょう':'のこっている',802,y+21,14,p.out?'#b8a2ac':'#b9e0ce');});
 button('バトルを もういちど',24,471,253,48,()=>{frame=0;paused=false;screen='battle';tick();});button('みんなの けっか',289,471,215,48,()=>{modal='matches';render();});button(g.players[0].hp<=0||g.phase==='end'?'さいごの けっか →':'つぎの おみせ →',521,471,415,48,next,true,'#a77837');
}
function drawModal(){buttons=[];rect(0,0,960,540,'#07121cef',0);rect(63,58,834,446,'#254452');button('とじる ×',775,69,105,38,closeModal);
 if(modal?.detail){const u=modal.detail,d=CARDS[u.id]||{name:'ちびロボ',f:0,tier:0,role:0};card(u,86,122,218,279,()=>{});text(NAMES[d.f]+' / '+ROLES[d.role]+' / '+'★'.repeat(d.tier),333,128,18,'#c5e2e2');text(d.name+(u.star?' ★スター':''),333,163,28,'#ffe4a0');let y=205;for(const line of describe(u))y=wrap(line,333,y,530,17)+9;
  const origin=modal.origin,p=g?.players[0];
  if(origin?.shop!==undefined){const count=[...p.board,...p.bench].filter(v=>v.id===u.id&&!v.star).length;text('もっている '+count+'まい / 3まいで ★スター',333,396,17,'#e2d09e');button('3コインで かう',333,436,323,46,()=>purchase(origin.shop),p.gold>=3&&g.canReceive(p,u.id), '#a77837');}
  else if(origin?.owned){button('ならべかえる',333,430,213,48,()=>{selected=u.uid;modal=null;render();});button('うる +1コイン',562,430,230,48,()=>{modal={sell:u.uid};detailReturn=null;render();},true,'#764a4a');}
  else text('なが おし・タップで いつでも かくにんできるよ',333,447,16,'#b6d4dc');
 }else if(modal?.sell){text('この なかまを うる？',104,142,27,'#ffe1a0');const u=[...g.players[0].board,...g.players[0].bench].find(v=>v.uid===modal.sell);if(u)card(u,110,190,184,215,()=>{});text('うると 1コイン もどるよ。',345,241,24,'#f3e4c9');text('つよくした なかまも チームから いなくなるよ。',345,282,17,'#d7dfe0');button('うる',345,369,200,54,()=>{checkpointUndo();g.sell(g.players[0],modal.sell);selected=null;modal=null;notice='うったよ。「うるまえに もどす」で とりけせるよ';render();},true,'#87534e');button('やめる',565,369,200,54,()=>{modal=null;render();});
 }else if(modal==='catalog'){text('カードずかん　60しゅるい',91,97,24,'#ffe2a2');const page=CARDS.slice(catalogPage*8,catalogPage*8+8);page.forEach((d,i)=>card({...d,star:false},91+i%4*193,125+Math.floor(i/4)*147,176,134));button('← まえ',91,438,160,45,()=>{catalogPage=(catalogPage+7)%8;render();});text((catalogPage+1)+' / 8',480,469,22,'#d9e6df','center');button('つぎ →',705,438,160,45,()=>{catalogPage=(catalogPage+1)%8;render();});
 }else if(modal==='reward'){text('★ ごほうびを 1まい えらぼう',91,110,26,'#ffe2a2');const p=g.players[0];(p.rewards[0]||[]).forEach((id,i)=>{const d=CARDS[id];card({...d,star:false},126+i*245,151,218,230);button('これにする',126+i*245,401,218,48,()=>{undoState=null;g.reward(p,i);if(!p.rewards.length)modal=null;render();},g.canReceive(p,id));});text('カードを タップで わざを かくにん。いっぱいなら なかまを うってね。',92,479,15,'#c1d7db');
 }else if(modal==='opponent'){const pair=g.pairs.find(a=>a.includes(0)),id=pair.find(x=>x!==0),op=g.players[id>=0?id:-id-2];text(op.name+'の まえの チーム',91,128,24,'#ffe2a2');text('こんかいの おかいものは まだ ひみつだよ。',91,168,17,'#cadbe2');(op.last||[]).forEach((u,i)=>card(u,91+i*156,230,145,172));if(!op.last)text('まだ はじめての バトルだよ',480,296,24,'#d0e3e3','center');
 }else if(modal==='ranks'){text('みんなの じゅんい',91,111,24,'#ffe2a2');g.standings().forEach((p,i)=>text(p.place+'い　'+p.name+'　♥ '+p.hp+'　おみせ '+'★'.repeat(p.tier)+(p.out?'　だつらく':''),103,156+i*39,19,p.id===0?'#ffe09c':'#cadfdf'));
 }else if(modal==='matches'){text('みんなの バトル',91,116,27,'#ffe2a2');g.results.forEach((r,i)=>{const a=g.players[r.x],b=g.players[r.y>=0?r.y:-r.y-2];text(a.name+' vs '+b.name,104,182+i*67,20,'#d3e5e5');text(r.winner<0?'ひきわけ / おたがい '+r.damage+'ダメージ':(r.winner===0?a.name:b.name)+'の かち / '+r.damage+'ダメージ',104,208+i*67,16,'#efd09f');});
 }else if(modal==='empty'){text('チームが からっぽだよ',101,155,30,'#ffe0a0');text('なかまを かうか、ひかえから チームに いれてね。',101,223,21,'#d1e4e5');button('おみせに もどる',101,352,350,59,()=>{modal=null;render();});button('このまま バトル',474,352,350,59,()=>{modal=null;showFight();},true,'#7b5c48');
 }else if(modal==='help'){text('あそびかた',91,108,26,'#ffe2a2');['① うえの おみせで なかまを かおう。','② したの チームは 5にん。ひかえは 3にん。','③ カードを タップ →「ならべかえる」で いどう。','④ おみせ★4で 3まい そろえると ★5が もらえる！','⑤ じゅんびOKで バトル。4いまで のこれば にゅうしょう。','⚔ こうげきは あたえる つよさ。♥ たいりょくは 0で おやすみ。','11せんめから ダメージ+1、つぎは+2。ひきわけも へるよ。','★5が のこって かつと 1まいにつき ダメージ+3！'].forEach((l,i)=>text(l,91,160+i*38,i>4?17:20,'#d4e7e4'));
 }else if(modal==='settings'){text('せってい',91,117,26,'#ffe2a2');button(sound?'おと ON':'おと OFF',130,164,310,54,()=>{sound=!sound;tone();render();});button(gentle?'うごき ひかえめ':'うごき あり',500,164,310,54,()=>{gentle=!gentle;render();});button('がめんを おおきく',130,252,680,54,()=>{if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>{});});text('おとの ON/OFFは この かいの あそびに はんえいするよ。',130,356,18,'#cadde1');text('あいことばで おみせの つづきから あそべるよ。',130,395,18,'#cadde1');}
}
function drawTitle(){text('あつめて、そだてて、かちのこる。',480,76,20,'#b9dce0','center');text('ひがしやま チームバトル！',480,121,36,'#ffe1a0','center');text('60しゅの なかま / CPU7にんと たいせん',480,154,17,'#bdd6dc','center');for(let f=0;f<5;f++){const x=39+f*178;rect(x,176,168,162,leader===f?'#3c6775':'#203c49');const d=CARDS.find(c=>c.f===f);if(!art(d,x+8,184,152,109))portrait(f,x+55,195,4);text(NAMES[f],x+84,321,21,COLORS[f],'center');buttons.push({label:NAMES[f]+'を えらぶ',x,y:176,w:168,h:162,fn:()=>{leader=f;render();}});}text(LEADER[leader],480,366,18,'#ead9b3','center');button(difficulty===0?'やさしい ✓':'やさしい',160,391,215,42,()=>{difficulty=0;render();});button(difficulty===1?'ふつう ✓':'ふつう',386,391,215,42,()=>{difficulty=1;render();});button('あそぶ →',614,391,190,42,start,true,'#a77837');button('はじめての れんしゅう',39,468,206,45,startTutorial);button('カードずかん',260,468,206,45,()=>{modal='catalog';render();});button('つづきから',480,468,206,45,openRestore);button('せってい',700,468,220,45,()=>{modal='settings';render();});}
function drawFinish(){const p=g.players[0];text(p.rank===1?'ゆうしょう！':p.rank<=4?'にゅうしょう！':'また チャレンジ！',480,139,37,'#ffe2a1','center');text('あなたは '+p.rank+'い',480,200,36,'#e5efdc','center');text(g.round+'ラウンド / '+NAMES[p.leader]+'の チーム',480,239,18,'#bad7dc','center');p.board.forEach((u,i)=>card(u,100+i*155,288,144,159));button('もういちど',194,474,256,45,start,true,'#a77837');button('タイトルへ',470,474,290,45,()=>{screen='title';g=null;modal=null;render();});}
function render(){if(fx&&fxAge>=(fx.type==='merge'?1500:950))fx=null;buttons=[];ctx.clearRect(0,0,960,540);const grad=ctx.createLinearGradient(0,0,960,540);grad.addColorStop(0,'#152e3b');grad.addColorStop(1,'#0d2532');ctx.fillStyle=grad;ctx.fillRect(0,0,960,540);text('ひがしやま チームバトル！',24,31,15,'#aac6cd');button('せってい',829,8,106,34,()=>{modal='settings';render();});
 if(screen==='tutorial')drawTutorial();else if(screen==='title')drawTitle();else {const p=g.players[0];text('ROUND '+g.round,24,68,24,'#ffe0a0');text('♥ '+Math.max(0,screen==='battle'?oldHearts:p.hp)+' / 25',195,67,23,'#ffb3c3');text('のこり '+g.players.filter(p=>p.hp>0).length+'にん',374,67,17,'#b8d4d8');button('あそびかた',793,46,142,34,()=>{modal='help';render();});if(g.round>=11)text('けっせん！ ダメージ +'+g.lateBonus(),548,67,16,'#ffbe85');if(screen==='prep')drawPrep();if(screen==='battle')drawBattle();if(screen==='result')drawStandings();if(screen==='finish')drawFinish();}
 drawPurchase();if(modal)drawModal();
 const key=JSON.stringify([screen,modal,buttons.map(b=>[b.label,b.x,b.y])]);if(key!==accessKey){accessKey=key;access.replaceChildren(...buttons.map((b,i)=>{const el=document.createElement('button');el.textContent=b.label;el.onclick=()=>buttons[i]?.fn();return el;}));}
}
function releasePointerDown(e){if(e.button!==0)return;const r=cv.getBoundingClientRect(),x=(e.clientX-r.left)*960/r.width,y=(e.clientY-r.top)*540/r.height,b=buttons.slice().reverse().find(b=>x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h);press=b?{b,x,y,id:e.pointerId,long:false}:null;if(b){cv.setPointerCapture?.(e.pointerId);if(b.inspect)holdTimer=setTimeout(()=>{if(press){press.long=true;b.inspect();}},480);}}
function releasePointerUp(e){clearTimeout(holdTimer);const item=press;press=null;if(item&&!item.long&&e.pointerId===item.id){const r=cv.getBoundingClientRect(),x=(e.clientX-r.left)*960/r.width,y=(e.clientY-r.top)*540/r.height;if(Math.abs(x-item.x)<16&&Math.abs(y-item.y)<16)item.b.fn();}}
function cancelPointer(){clearTimeout(holdTimer);press=null;}
function contextInspect(e){e.preventDefault();const r=cv.getBoundingClientRect(),x=(e.clientX-r.left)*960/r.width,y=(e.clientY-r.top)*540/r.height;const b=buttons.slice().reverse().find(b=>b.inspect&&x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h);if(b)b.inspect();}
function checksum(s){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return(h>>>0).toString(36);}
async function encodeSave(e){const raw=JSON.stringify(e.checkpoint()),bytes=new TextEncoder().encode(raw);let data=bytes,mode='J';if(typeof CompressionStream!=='undefined'){data=new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer());mode='G';}let binary='';for(const n of data)binary+=String.fromCharCode(n);return 'HB1'+mode+'.'+btoa(binary)+'.'+checksum(raw);}
async function decodeSave(code){const a=code.trim().split('.');if(a.length!==3||!/^HB1[JG]$/.test(a[0])||a[1].length>50000)throw Error('あいことばが ちがうよ');let bytes=Uint8Array.from(atob(a[1]),c=>c.charCodeAt(0));if(a[0]==='HB1G'){if(typeof DecompressionStream==='undefined')throw Error('このブラウザでは よめないよ');const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip')),reader=stream.getReader(),parts=[];let size=0;while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>100000){await reader.cancel();throw Error('あいことばが ながすぎるよ');}parts.push(value);}bytes=new Uint8Array(size);let pos=0;for(const p of parts){bytes.set(p,pos);pos+=p.length;}}const raw=new TextDecoder().decode(bytes);if(checksum(raw)!==a[2])throw Error('あいことばが こわれているよ');return Engine.restore(JSON.parse(raw));}
function saveDialog(title,value,restore=false){const box=document.getElementById('save-dialog'),input=document.getElementById('save-code');document.getElementById('save-title').textContent=title;input.value=value;document.getElementById('restore-button').hidden=!restore;document.getElementById('copy-button').hidden=restore;document.getElementById('save-note').textContent=restore?'あいことばを はりつけてね。':'チームを そのまま のこすため ながい あいことばだよ。コピーして ほぞんしてね。';box.showModal();input.focus();input.select();}
async function openSave(){try{saveDialog('おみせの つづきを ほぞん',await encodeSave(g));}catch(err){notice=err.message;render();}}
function openRestore(){saveDialog('あいことばで つづきから','',true);}
async function restoreFromDialog(){try{g=await decodeSave(document.getElementById('save-code').value);difficulty=g.difficulty;leader=g.players[0].leader;screen='prep';modal=null;selected=null;fx=null;undoState=null;document.getElementById('save-dialog').close();notice='つづきから あそべるよ！';render();}catch(err){document.getElementById('save-note').textContent=err.message||'あいことばが ちがうよ';}}
function music(now){if(!sound||!audio||document.hidden)return;if(now-music.last<600)return;music.last=now;const notes=[261.63,329.63,392,329.63,293.66,349.23,440,349.23];const o=audio.createOscillator(),v=audio.createGain();o.type='triangle';o.frequency.value=notes[music.note++%notes.length]/2;v.gain.setValueAtTime(.012,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.42);o.connect(v).connect(audio.destination);o.start();o.stop(audio.currentTime+.45);}music.note=0;music.last=0;
